### ISSUE TITLE
В отелях грузит шапку от nemo travel

### ISSUE THREAD

**Issue by asminog** [NemoTravel/nemo.travel.frontend#10]
В авиа шапки нет, а в отелях есть.

![2017-03-15 13 48 31](https://cloud.githubusercontent.com/assets/1555548/23945132/6730b26a-0986-11e7-9301-e2ab461da1cc.png)
![2017-03-15 13 49 38](https://cloud.githubusercontent.com/assets/1555548/23945131/673024d0-0986-11e7-9caa-2b395edbdcf5.png)

**Comment by ecrofeg** [comment]
Fixed
