### ISSUE TITLE
Префикс для ссылки заказа

### ISSUE THREAD

**Issue by akudovich** [NemoTravel/nemo.travel.frontend#12]
При заказе открывает "/create__hotel_order" в корне сайта, нужна возможность указывать префикс

**Comment by ecrofeg** [comment]
Добавил параметр createOrderLinkPrefixHotels, добавляется вот сюда в файлике index.php http://storage5.static.itmages.com/i/17/0316/h_1489683792_5565899_45e6b8b96d.jpeg
