### ISSUE TITLE
Автокомплит по отелям

### ISSUE THREAD

**Issue by asminog** [NemoTravel/nemo.travel.frontend#15]
Не работает, хотя пишет "укажите город или отель"

**Comment by ecrofeg** [comment]
Обсуждали с Данилом. Сделали поиск по имени отеля на поисковой выдаче, слева, в разделе с фильтрами (дабы не ограничивать искусственно выдачу).

http://storage9.static.itmages.com/i/17/0628/h_1498656798_4313518_14760da950.jpeg
