### ISSUE TITLE
Не работает смена валюты в отелях

### ISSUE THREAD

**Issue by akudovich** [NemoTravel/nemo.travel.frontend#16]
Вызов события $(document).trigger('cc:changeCurrency', { currency: 'EUR' });
и/или установка cookie 'ccCurrency' не дает нужного эффекта в отелях, в авиа работает

**Comment by ecrofeg** [comment]
Fixed.
Уточню, чтобы всё верно работало, необходимо сконфигурировать курсы валют.
https://github.com/NemoTravel/nemo.travel.frontend/wiki/%D0%9A%D0%BE%D0%BD%D0%B2%D0%B5%D1%80%D1%82%D0%B5%D1%80-%D0%B2%D0%B0%D0%BB%D1%8E%D1%82
