### ISSUE TITLE
Можно указать чекин и чекаут на одну дату

### ISSUE THREAD

**Issue by akudovich** [NemoTravel/nemo.travel.frontend#19]
http://clip2net.com/s/3JYz0sN

**Comment by akudovich** [comment]
Все еще можно: https://monosnap.com/file/JSIPlkJfo1saWQCB9BjYZqagVd36m3

**Comment by akudovich** [comment]
Переоткройте пожалуйста

**Comment by ecrofeg** [comment]
Поправили, сбросьте кеши и localstorage
