### ISSUE TITLE
Меню предыдущие поиски перебрасывает в корень сайта

### ISSUE THREAD

**Issue by akudovich** [NemoTravel/nemo.travel.frontend#23]
+ при переходе на страницу по прямой ссылке на пустой поиск не срабатывает локализация
![2017-05-24 10-50-58](https://cloud.githubusercontent.com/assets/26432474/26392376/140ee5a0-406f-11e7-83a1-b62a46408350.png)

**Comment by ecrofeg** [comment]
Fixed

**Comment by asminog** [comment]
Все еще перебрасывает в корень

**Comment by akudovich** [comment]
![2017-06-16 10-17-43](https://user-images.githubusercontent.com/26432474/27216170-34a8383c-527d-11e7-9069-1cb57eca15a1.png)
+ 2 ссылки в корень

**Comment by EvgenyVetrov** [comment]
![1498745394817](https://user-images.githubusercontent.com/15690133/27691857-f70f788e-5ced-11e7-8016-fe936e5ed79c.jpg)

в Авиа тоже проблемка

**Comment by ecrofeg** [comment]
Поправили и авиа и отели.
Теперь будут красивые кнопочки и они перебрасывают куда нужно.
http://storage2.static.itmages.com/i/17/0719/h_1500468844_8947595_e907711fa0.jpeg

**Comment by akudovich** [comment]
Меню предыдущие поиски все еще перебрасывает в корень сайта

**Comment by akudovich** [comment]
Переоткройте пожалуйста

**Comment by ecrofeg** [comment]
Обновил виджет
