### ISSUE TITLE
ошибки

### ISSUE THREAD

**Issue by akudovich** [NemoTravel/nemo.travel.frontend#28]
При переходе на карточку отеля:
![2017-05-26 09-37-29](https://cloud.githubusercontent.com/assets/26432474/26486276/11077c74-4203-11e7-89f9-3d28b9633b93.png)
по прямой ссылке на карточку отеля + иногда на форме поиска (форма поиска не показывается):
![metropol moscow hotel 2017-05-26 11-03-11](https://cloud.githubusercontent.com/assets/26432474/26486275/109c7f96-4203-11e7-8c51-2d62a2df4179.png)

**Comment by ecrofeg** [comment]
* Ошибка с гугл картами возникла из-за того, что мы убрали захардкоженый API ключ Google Maps. Руководство по подключению своего ключа: https://github.com/NemoTravel/nemo.travel.frontend/wiki/Google-Maps
* Вторая ошибка может возникать из-за проблем с нашим справочником городов. Проблема в процессе исправления.
