### ISSUE TITLE
Поиск отелей. Предыдущие поиски. Выводится лишняя запятая в начале строки

### ISSUE THREAD

**Issue by akudovich** [NemoTravel/nemo.travel.frontend#33]
https://monosnap.com/file/ONsIyc1idRUj4ELGaseVwG7xP2aDBO

**Comment by akudovich** [comment]
+ нет города в критериях поиска https://monosnap.com/file/5XAcG1GQNFl5MkXYD8mAw2aEYkoo48

**Comment by ecrofeg** [comment]
Исправлено, вскоре будет выкачено.
