### ISSUE TITLE
Подсвечивать оптимальные варианты в результатах поиска "списком" 

### ISSUE THREAD

**Issue by EvgenyVetrov** [NemoTravel/nemo.travel.frontend#37]
Если результаты поиска билетов выводить плиткой, то в списке всех билетов подсвечиваются оптимальные варианты (это ок):
![image](https://user-images.githubusercontent.com/15690133/28006544-6a4e7864-6558-11e7-98da-a9dfbe228170.png)

Если выбрать представление всех билетов "списком", то подсветки оптимальных вариантов уже нет:
![image](https://user-images.githubusercontent.com/15690133/28006398-cbba4048-6557-11e7-9e20-8539e5bca700.png)

Стоит сделать подсветку оптимальных вариантов в представлении "списком" для единообразия взаимодействия пользователей с системой.

**Comment by ecrofeg** [comment]
Подсветка "оптимальных" перелётов - это не задача виджета Nemo. Это реализовано на вашей стороне.
