### ISSUE TITLE
Неправильная подсказка по отмене

### ISSUE THREAD

**Issue by akudovich** [NemoTravel/nemo.travel.frontend#43]
Если для номера приходит 2 правила отмены:
![vienna house magic circus paris 2017-07-31 14-40-17](https://user-images.githubusercontent.com/26432474/28776288-ae1ff6ec-75fe-11e7-84dd-09eaf7b2dcca.png)

**Comment by akudovich** [comment]
https://monosnap.com/file/0yJvSNTQkc0YySTtl1xqEhP8ySwKPN

**Comment by ecrofeg** [comment]
Исправлено пару недель назад.
