### ISSUE TITLE
Поиск отелей. Едет верстка в окне кол-во мест

### ISSUE THREAD

**Issue by akudovich** [NemoTravel/nemo.travel.frontend#47]
http://take.ms/7gTbw

**Comment by ecrofeg** [comment]
Это ваши подключенные стили. В виджете всё в порядке: http://storage3.static.itmages.com/i/17/0817/h_1502975742_7840837_d5a40432ef.jpeg

**Comment by asminog** [comment]
конфликтует JQueryUI - а это распространенная либа

**Comment by akudovich** [comment]
Переоткройте пожалуйста.

**Comment by ecrofeg** [comment]
Мы подключали в нашу систему `jQuery-UI` и другие популярные библиотеки из их официальных репозиториев (в базовых темах оформления) - все работает нормально. 

Проблемы возникают при подключении каких-то кастомных тем оформления jQuery, как в вашем случае, тема `smoothness`: `https://dev.bizontrip.com/assets/cef82919/themes/smoothness/jquery-ui.css`

Боюсь мы не в состоянии подгонять внешний вид системы под все существующие темы, поэтому предлагаю такой вариант: 
* при скачивании jQuery-UI можно указать CSS-класс, в который будет "обернута" библиотека: https://image.prntscr.com/image/UE5jsHd1SzqdecAew8N5VA.png
* в результате CSS-файл будет выглядеть примерно так: https://image.prntscr.com/image/MaOjulpoSZeTZVpWY5Vqyg.png
