### ISSUE TITLE
Для случая без вариантов не писать сообщение о сбросе фильтров

### ISSUE THREAD

**Issue by EvgenyVetrov** [NemoTravel/nemo.travel.frontend#49]
В виджете авиа есть такая загвоздка:
![image](https://user-images.githubusercontent.com/15690133/29622352-e0db1e10-882b-11e7-8de8-19ce62cf8e7f.png)

Очень хотелось бы скрывать фразу "Вы можете сбросить следующие фильтры" когда вариантов то и нет.

**Comment by ecrofeg** [comment]
Не воспроизводится, точно не сломали что-то у себя?
