### ISSUE TITLE
Загрузка svg 

### ISSUE THREAD

**Issue by akudovich** [NemoTravel/nemo.travel.frontend#6]
на роуте /hotels/results/422697 пытается грузить из корня а не из baseUrl:

> http://nemo.local/css/images/ui/ui-loader-circle.svg
> http://nemo.local/img/show_on_list.png
> http://nemo.local/css/images/hotels_results_sprite.svg
> http://nemo.local/css/images/hsf-sprite.svg
> http://nemo.local/css/images/hotels_results_sprite.svg
> http://nemo.local/css/images/ui/checkbox_sprite.svg
> http://nemo.local/img/no_hotel.svg
> http://nemo.local/img/no_hotel.png
> http://nemo.local/css/images/hotels_results_services_sprite.svg

**Comment by ecrofeg** [comment]
Fixed
