### ISSUE TITLE
В поле аэропорт прибытия выводится и город и аэропорт

### ISSUE THREAD

**Issue by EvgenyVetrov** [NemoTravel/nemo.travel.frontend#63]
При поиске перелетов на широком (примерно 1600px+) экране это доставляет неудобства. Выглядит следующим образом:
![image](https://user-images.githubusercontent.com/15690133/33208917-9ef1b71a-d124-11e7-8866-fb4221fb3e90.png)

По идее в это поле должно выводиться только название аэропорта без города и тогда все будет гораздо лучще.

в определенных случаях, если перезагрузить страницу, заново поиск начать, выбрать другую дату и подобные действия воспроизвести, все становится правильно (на скрине локальный проект и он ведет себя так же как и проект со скриншота выше):

![image](https://user-images.githubusercontent.com/15690133/33209062-3da51d66-d125-11e7-97e6-cf7ff3e0a462.png)

Полное видео того как воспроизвелось такое поведение: https://drive.google.com/open?id=1RZioDU6t0yn2MGw4w4NmA7SRJ8ll0H_Q

Попробовал найти концы, откуда нокаут берет этот arrAirp, но увы, быстро найти не получилось выходы.

**Comment by ecrofeg** [comment]
Проблема там не в JS, а в нашем собственном справочнике городов\аэропортов.
Это легаси\костыли, которые когда-то просили внести наши клиенты-агенты.
Многие агенты просили добавить в название аэропорта еще и название города, к которому он относится, чтобы улучшить результаты автокомплита аэропортов.

Избавиться от этого пока, увы, не можем.
