### ISSUE TITLE
Отели: ошибка при отображении результатов поиска

### ISSUE THREAD

**Issue by asminog** [NemoTravel/nemo.travel.frontend#64]
В виджете отелей при отображении результатов поиск стабильно воспроизводится ошибка:
<img width="1622" alt="hotels" src="https://user-images.githubusercontent.com/1555548/34402167-0de2618c-ebb1-11e7-8594-6edb77ee393e.png">

**Comment by ecrofeg** [comment]
Исправлено пару недель назад.
