### ISSUE TITLE
Предустановка в форму отелей

### ISSUE THREAD

**Issue by akudovich** [NemoTravel/nemo.travel.frontend#8]
Добавить возможность предустановки значений в форму отелей по аналогии с авиа

Необходима возможность установить кол-во гостей.

**Comment by ecrofeg** [comment]
Пример использования:
`/hotels/search/123123-20180609-20180610-ADT1CLD2-ADT1CLD1-ADT1`

Где:
* `123123` - айдишник отеля\города, но справочник городов поставщиков\поиск по отелям пока в разработке, поэтому это не работает (необязательный параметр)
* `20180609` - дата заезда (необязательный параметр)
* `20180610` - дата выезда (необязательный параметр)
* `ADT1CLD2` - первая комната, 1 взрослый и 2 ребенка (необязательный параметр)
* `ADT1CLD1` - вторая комната, 1 взрослый и 1 ребенка, и т.д. (необязательный параметр)
