### ISSUE TITLE
При просмотре информации об отеле нет прокрутки

### ISSUE THREAD

**Issue by asminog** [NemoTravel/nemo.travel.frontend#9]
Роут: /hotels/results/422710/50779995

Ошибка в логе:

> Uncaught ReferenceError: Unable to process binding "foreach: function (){return elements }"
> Message: Unable to process binding "if: function (){return !active }"
> Message: Unable to process binding "text: function (){return $data.i18n ? $data.i18n:$root.i18n('CommonBreadCrumbs',title) }"
> Message: title is not defined
>     at text (eval at parseBindingsString (knockout-3.2.0.js:59), <anonymous>:3:119)
>     at update (knockout-3.2.0.js:88)
>     at function.a.j.o (knockout-3.2.0.js:63)
>     at k (knockout-3.2.0.js:42)
>     at Object.a.s.a.j (knockout-3.2.0.js:45)
>     at knockout-3.2.0.js:63
>     at Object.u (knockout-3.2.0.js:10)
>     at f (knockout-3.2.0.js:62)
>     at h (knockout-3.2.0.js:60)
>     at g (knockout-3.2.0.js:60)

**Comment by ecrofeg** [comment]
Fixed
